### ISSUE TITLE
With latest docker-image (2022.04.01) Web-GUI (https) doesn't work anymore: ./run: line 32:  Segmentation fault  lighttpd -D -f /etc/lighttpd/lighttpd.conf

### ISSUE THREAD

**Issue by thomasmerz** [pi-hole/docker-pi-hole#1046]
This is a: **Bug**  

https (as described [here](https://discourse.pi-hole.net/t/enabling-https-for-your-pi-hole-web-interface/5771/112)) isn't working any more. http works. dns works.

## Details
With latest docker-image (2022.04.01) Web-GUI (https) doesn't work anymore:

```
🇩🇪  ✔ ~ [master|✔]
15:40 # docker images | grep pi
pihole/pihole                      latest       49d9294069e4   3 hours ago     302MB
pihole/pihole                      <none>       867e50a3f3b0   15 hours ago    302MB
…
pihole/pihole                      <none>       ab22a9e4a994   6 weeks ago     298MB
🇩🇪  ✔ ~ [master|✔]
15:40 # systemctl status pihole -l
● pihole.service - pihole
   Loaded: loaded (/root/etc/systemd/system/pihole.service; enabled; vendor preset: enabled)
   Active: active (running) since Sat 2022-04-02 15:37:26 CEST; 3min 0s ago
  Process: 6364 ExecStop=/usr/bin/docker stop -t 2 pihole (code=exited, status=0/SUCCESS)
 Main PID: 6504 (docker)
    Tasks: 8 (limit: 4582)
   CGroup: /system.slice/pihole.service
           └─6504 /usr/bin/docker start -a pihole

Apr 02 15:38:21 ubuntu-cx11-02 docker[6504]: lighttpd: no process found
Apr 02 15:38:21 ubuntu-cx11-02 docker[6504]: Starting lighttpd
Apr 02 15:38:21 ubuntu-cx11-02 docker[6504]: 2022-04-02 15:38:21: mod_openssl.c.2475) SSL: ssl.use-sslv2 is deprecated and will soon be removed.  It is disabled by default.  Many modern TLS libraries no longer support SSLv2.
Apr 02 15:38:21 ubuntu-cx11-02 docker[6504]: 2022-04-02 15:38:21: mod_openssl.c.2482) SSL: ssl.use-sslv3 is deprecated and will soon be removed.  It is disabled by default.  Many modern TLS libraries no longer support SSLv3.
Apr 02 15:38:24 ubuntu-cx11-02 docker[6504]: ./run: line 32:  2902 Segmentation fault      (core dumped) lighttpd -D -f /etc/lighttpd/lighttpd.conf
Apr 02 15:38:24 ubuntu-cx11-02 docker[6504]: Stopping lighttpd
Apr 02 15:38:24 ubuntu-cx11-02 docker[6504]: lighttpd: no process found
Apr 02 15:38:24 ubuntu-cx11-02 docker[6504]: Starting lighttpd
Apr 02 15:38:24 ubuntu-cx11-02 docker[6504]: 2022-04-02 15:38:24: mod_openssl.c.2475) SSL: ssl.use-sslv2 is deprecated and will soon be removed.  It is disabled by default.  Many modern TLS libraries no longer support SSLv2.
Apr 02 15:38:24 ubuntu-cx11-02 docker[6504]: 2022-04-02 15:38:24: mod_openssl.c.2482) SSL: ssl.use-sslv3 is deprecated and will soon be removed.  It is disabled by default.  Many modern TLS libraries no longer support SSLv3.
```
## Related Issues
- [x] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 
  Issue #1043 also reports problems with this version, but it deals with another problem.

## How to reproduce the issue 

1. Environment data
  * Operating System: Ubuntu 20.04.4 LTS with Docker version 20.10.7, build 20.10.7-0ubuntu5~20.04.2 and Ubuntu 18.04.6 LTS with Docker version 20.10.7, build 20.10.7-0ubuntu5~18.04.3
  * Hardware: VM running in Hetzner Cloud
  * Kernel Architecture: x86/amd64
  * Docker Install Info and version: see above
  * Hardware architecture: x86

2. docker-compose.yml contents, docker run shell command, or paste a screenshot of any UI based configuration of containers here
  ```
# cat docker-compose.yml|grep -v PASS
version: "3"

# https://github.com/pi-hole/docker-pi-hole/blob/master/README.md

services:
  pihole:
    hostname: 'pihole-nbg1-dc3'
    container_name: pihole
    image: pihole/pihole:latest
    #image: pihole/pihole:v5.7
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      #- "67:67/udp"
      - "12345:80/tcp"
      - "23456:443/tcp"
    # https://github.com/pi-hole/docker-pi-hole/#environment-variables
    environment:
      TZ: 'Europe/Berlin'
    # Volumes store your data between container upgrades
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
      # Enabling HTTPS for your Pi-hole Web Interface
      # https://discourse.pi-hole.net/t/enabling-https-for-your-pi-hole-web-interface/5771
      - './etc-lighttpd-external.conf:/etc/lighttpd/external.conf'
      - './etc-letsencrypt:/etc/letsencrypt/'
      # run `touch ./var-log/pihole.log` first unless you like errors
      # - './var-log/pihole.log:/var/log/pihole.log'
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
      - CAP_SYS_NICE
    restart: unless-stopped
    #network_mode: 'host'
    #network_mode: 'bridge'  # https://forums.docker.com/t/docker-errors-invalidargument-host-network-mode-is-incompatible-with-port-bindings/103492
```
4. any additional info to help reproduce
  xxx

## These common fixes didn't work for my issue

- [x] I have tried removing/destroying my container, and re-creating a new container - with `pihole/pihole:2022.02.1` everything was fine and is fine again 🤷🏻‍♂️ 
- [ ] I have tried fresh volume data by backing up and moving/removing the old volume data
- [ ] I have tried running the stock `docker run` example(s) in the readme (removing any customizations I added)
- [ ] I have tried a newer or older version of Docker Pi-hole (depending what version the issue started in for me)
- [ ] I have tried running without my volume data mounts to eliminate volumes as the cause

If the above debugging / fixes revealed any new information note it here.
Add any other debugging steps you've taken or theories on root cause that may help.

**Comment by PromoFaux** [comment]
Hmmm, OK. This is likely related to the differences in buster and bullseye

This PR sought to sort that out:

https://github.com/pi-hole/docker-pi-hole/pull/1009

But I had second thoughts after merging it as it also involved generating a self-signed certificate - so it was reverted. 

However, we did add `lighttpd-mod-ssl` to the base image, but it is not enabled:

https://github.com/pi-hole/docker-base-images/commit/4051456c10bfd7775e8b36ca4f7529f5d8a1155d

What does your `/etc/lighttpd/lighttpd.conf` look like, though you shouldn't be making changes to that - should be in `/etc/lighttpd/external.conf`, or maybe via a file in `/etc/lighttpd/conf-enabled/`

Debug token too, please!

**Comment by thomasmerz** [comment]
```
root@pihole-hel1-dc2:/# cat /etc/lighttpd/lighttpd.conf
# Pi-hole: A black hole for Internet advertisements
# (c) 2017 Pi-hole, LLC (https://pi-hole.net)
# Network-wide ad blocking via your own hardware.
#
# Lighttpd config for Pi-hole
#
# This file is copyright under the latest version of the EUPL.
# Please see LICENSE file for your rights under this license.

###############################################################################
#     FILE AUTOMATICALLY OVERWRITTEN BY PI-HOLE INSTALL/UPDATE PROCEDURE.     #
# ANY CHANGES MADE TO THIS FILE AFTER INSTALL WILL BE LOST ON THE NEXT UPDATE #
#                                                                             #
#              CHANGES SHOULD BE MADE IN A SEPARATE CONFIG FILE:              #
#                         /etc/lighttpd/external.conf                         #
###############################################################################

server.modules = (
    "mod_access",
    "mod_accesslog",
    "mod_auth",
    "mod_expire",
    "mod_redirect",
    "mod_setenv",
    "mod_rewrite"
)

server.document-root        = "/var/www/html"
server.error-handler-404    = "/pihole/index.php"
server.upload-dirs          = ( "/var/cache/lighttpd/uploads" )
server.errorlog             = "/var/log/lighttpd/error.log"
server.pid-file             = "/run/lighttpd.pid"
server.username             = "www-data"
server.groupname            = "www-data"
server.port                 = 80
accesslog.filename          = "/var/log/lighttpd/access.log"
accesslog.format            = "%{%s}t|%V|%r|%s|%b"

index-file.names            = ( "index.php", "index.html", "index.lighttpd.html" )
url.access-deny             = ( "~", ".inc", ".md", ".yml", ".ini" )
static-file.exclude-extensions = ( ".php", ".pl", ".fcgi" )

mimetype.assign = (
    ".ico"   => "image/x-icon",
    ".jpeg"  => "image/jpeg",
    ".jpg"   => "image/jpeg",
    ".png"   => "image/png",
    ".svg"   => "image/svg+xml",
    ".css"   => "text/css; charset=utf-8",
    ".html"  => "text/html; charset=utf-8",
    ".js"    => "text/javascript; charset=utf-8",
    ".json"  => "application/json; charset=utf-8",
    ".map"   => "application/json; charset=utf-8",
    ".txt"   => "text/plain; charset=utf-8",
    ".eot"   => "application/vnd.ms-fontobject",
    ".otf"   => "font/otf",
    ".ttc"   => "font/collection",
    ".ttf"   => "font/ttf",
    ".woff"  => "font/woff",
    ".woff2" => "font/woff2"
)

# Add user chosen options held in external file
# This uses include_shell instead of an include wildcard for compatibility
include_shell "cat external.conf 2>/dev/null"

# default listening port for IPv6 falls back to the IPv4 port
include_shell "/usr/share/lighttpd/use-ipv6.pl " + server.port

# Prevent Lighttpd from enabling Let's Encrypt SSL for every blocked domain
#include_shell "/usr/share/lighttpd/include-conf-enabled.pl"
include_shell "find /etc/lighttpd/conf-enabled -name '*.conf' -a ! -name 'letsencrypt.conf' -printf 'include \"%p\"\n' 2>/dev/null"

# If the URL starts with /admin, it is the Web interface
$HTTP["url"] =~ "^/admin/" {
    # Create a response header for debugging using curl -I
    setenv.add-response-header = (
        "X-Pi-hole" => "The Pi-hole Web interface is working!",
        "X-Frame-Options" => "DENY"
    )
}

# Block . files from being served, such as .git, .github, .gitignore
$HTTP["url"] =~ "^/admin/\.(.*)" {
    url.access-deny = ("")
}

# allow teleporter and API qr code iframe on settings page
$HTTP["url"] =~ "/(teleporter|api_token)\.php$" {
    $HTTP["referer"] =~ "/admin/settings\.php" {
        setenv.add-response-header = ( "X-Frame-Options" => "SAMEORIGIN" )
    }
}

# Default expire header
expire.url = ( "" => "access plus 0 seconds" )
root@pihole-hel1-dc2:/#
```

and

```
root@pihole-hel1-dc2:/# cat /etc/lighttpd/external.conf
# inspired/taken from:
# https://discourse.pi-hole.net/t/enabling-https-for-your-pi-hole-web-interface/5771

$HTTP["host"] == "merz-vpn.mooo.com" {
  # Ensure the Pi-hole Block Page knows that this is not a blocked domain
  setenv.add-environment = ("fqdn" => "true")

  # Enable the SSL engine with a LE cert, only for this specific host
  $SERVER["socket"] == ":443" {
    ssl.engine = "enable"
    ### https://redmine.lighttpd.net/projects/1/wiki/HowToSimpleSSL
    ssl.pemfile = "/etc/letsencrypt/fullchain.pem"
    ssl.privkey = "/etc/letsencrypt/key.pem"
    #ssl.pemfile = "/etc/letsencrypt/combined.pem"  ## muss aus key.pem und cert.pem zusammengefügt werden.
    #ssl.ca-file = "/etc/letsencrypt/fullchain.pem"
    ###
    ssl.honor-cipher-order = "enable"
    ssl.cipher-list = "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH"
    ssl.use-sslv2 = "disable"
    ssl.use-sslv3 = "disable"
  }

  # Redirect HTTP to HTTPS
### REDIRECTING MIGHT BREAK GITHUB-UPPTIME-MONITORING
### IF CERT IS NOT FROM THIS HOST!
### USE IP IIN URL NSTEAD OF FHOSTNAME "SOLVES" THIS,
### BECAUSE REDIRECTION ONLY OCCURS FOR HOSTNAME…
# rewrite protocol + port
# https://stackoverflow.com/q/18476860
$HTTP["scheme"] == "http" {
###    $HTTP["host"] =~ ".*" {
    $HTTP["host"] =~ "([^:/]+)" {
      url.redirect = ( "^/(.*)" => "https://%1:33443/$1" )
###      url.redirect = (".*" => "https://%0$0")
    }
  }
}

# fix 'Warning: please add "mod_openssl" to server.modules list in lighttpd.conf.  A future release of lighttpd 1.4.x *will not* automatically load mod_openssl and lighttpd *will not* use SSL/TLS where your lighttpd.conf contains ssl.* directives'
# https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=907909
server.modules += ( "mod_openssl" )

root@pihole-hel1-dc2:/#
```

**Comment by thomasmerz** [comment]
Running again with `2022.04.01` and debug-token:
> [✓] Your debug token is: https://tricorder.pi-hole.net/dJ3BdrFz/

**Comment by thomasmerz** [comment]
Regarding my /etc/lighttpd directory:
```
root@pihole-hel1-dc2:/etc/lighttpd# find . -ls
   545021      8 drwxr-xr-x   1 pihole   root         4096 Apr  2 16:25 .
   545623      4 -rw-r--r--   1 root     root         3692 Apr  2 16:25 ./lighttpd.conf
   545022      4 drwxr-xr-x   1 root     root         4096 Apr  2 16:25 ./conf-enabled
   539539      0 lrwxrwxrwx   1 root     root           38 Mar 29 00:09 ./conf-enabled/99-unconfigured.conf -> ../conf-available/99-unconfigured.conf
   545663      4 -rw-r--r--   1 root     root          773 Apr  2 16:25 ./conf-enabled/15-fastcgi-php.conf
   545023      0 lrwxrwxrwx   1 root     root           33 Apr  2 13:03 ./conf-enabled/10-fastcgi.conf -> ../conf-available/10-fastcgi.conf
   539497      4 drwxr-xr-x   2 root     root         4096 Mar 29 00:09 ./conf-available
   539519      4 -rw-r--r--   1 root     root           38 Feb 17  2021 ./conf-available/10-usertrack.conf
   539499      4 -rw-r--r--   1 root     root          725 Jan 10 08:38 ./conf-available/05-setenv.conf
   539504      4 -rw-r--r--   1 root     root          128 Feb 17  2021 ./conf-available/10-evhost.conf
   539516      4 -rw-r--r--   1 root     root          460 Feb 17  2021 ./conf-available/10-status.conf
   539537      4 -rw-r--r--   1 root     root          843 Feb 17  2021 ./conf-available/README
   539508      4 -rw-r--r--   1 root     root           82 Feb 17  2021 ./conf-available/10-no-www.conf
   539513      4 -rw-r--r--   1 root     root          449 Feb 17  2021 ./conf-available/10-sockproxy.conf
   539501      4 -rw-r--r--   1 root     root          396 Feb 17  2021 ./conf-available/10-cgi.conf
   539518      4 -rw-r--r--   1 root     root          450 Feb 17  2021 ./conf-available/10-userdir.conf
   539530      4 -rw-r--r--   1 root     root          570 Jan 10 08:38 ./conf-available/15-fastcgi-php.conf
   539505      4 -rw-r--r--   1 root     root          104 Feb 17  2021 ./conf-available/10-expire.conf
   539506      4 -rw-r--r--   1 root     root          177 Feb 17  2021 ./conf-available/10-fastcgi.conf
   539511      4 -rw-r--r--   1 root     root          253 Feb 17  2021 ./conf-available/10-rrdtool.conf
   539500      4 -rw-r--r--   1 root     root           91 Feb 17  2021 ./conf-available/10-accesslog.conf
   539507      4 -rw-r--r--   1 root     root           42 Feb 17  2021 ./conf-available/10-flv-streaming.conf
   539515      4 -rw-r--r--   1 root     root          353 Jan 10 08:38 ./conf-available/10-ssl.conf
   539510      4 -rw-r--r--   1 root     root          176 Feb 17  2021 ./conf-available/10-rewrite.conf
   539536      4 -rw-r--r--   1 root     root          162 Feb 17  2021 ./conf-available/99-unconfigured.conf
   539520      4 -rw-r--r--   1 root     root          168 Jan 10 08:37 ./conf-available/11-extforward.conf
   539509      4 -rw-r--r--   1 root     root          849 Feb 17  2021 ./conf-available/10-proxy.conf
   539503      4 -rw-r--r--   1 root     root           36 Feb 17  2021 ./conf-available/10-evasive.conf
   539535      4 -rw-r--r--   1 root     root          508 Feb 17  2021 ./conf-available/90-debian-doc.conf
   539502      4 -rw-r--r--   1 root     root           63 Feb 17  2021 ./conf-available/10-dir-listing.conf
   539522      4 -rw-r--r--   1 root     root          355 Jan 10 08:38 ./conf-available/15-fastcgi-php-fpm.conf
   539498      4 -rw-r--r--   1 root     root          919 Jan 10 08:38 ./conf-available/05-auth.conf
   539512      4 -rw-r--r--   1 root     root          398 Feb 17  2021 ./conf-available/10-simple-vhost.conf
   539514      4 -rw-r--r--   1 root     root           99 Feb 17  2021 ./conf-available/10-ssi.conf
   545026      4 -rw-r--r--   1 root     root         3692 Apr  2 13:03 ./lighttpd.conf.orig
   265391      4 -rw-r--r--   1 root     root         1750 Apr  2 16:13 ./external.conf
```

**Comment by rdwebdesign** [comment]
Please, could you try `pihole/pihole:2022.04.2beta` image (no need to add NET_ADMIN capability)?

**Comment by thomasmerz** [comment]
`pihole/pihole:2022.04.2beta` didn't solve this: `https://tricorder.pi-hole.net/AzJAKhbE/`  

http 🆗   
dns 🆗   
https 🚫

**Comment by hhessel** [comment]
Can confirm that it doesn't work with beta either on my end. Seems to be related to segmentation fault already outlined above.

**Comment by rdwebdesign** [comment]
Regarding SSL warnings:

You are receiving these warnings because options `ssl.use-sslv2` and `ssl.use-sslv3` are deprecated.
You should remove them. After that the warnings should be gone.

IF you want to limit SSL support you could try `ssl.openssl.ssl-conf-cmd = ("MinProtocol" => "TLSv1.2")`, but I'm not sure this is necessary with the current `lighttpd` version.

`ssl.cipher-list` is deprecated too. 
Try to replace it with `ssl.openssl.ssl-conf-cmd = ("CipherString" => ... )`.

Example:

```conf
    ssl.openssl.ssl-conf-cmd = ("MinProtocol" => "TLSv1.2",
                                "CipherString" => "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH")
```

Reference:
https://redmine.lighttpd.net/projects/lighttpd/wiki/Docs_SSL

**Comment by hhessel** [comment]
This doesn't seem to be a problem with the config files itself. Even after refactoring the config files to the new syntax that you mentioned @rdwebdesign the segementation error still appears. I also don't understand why the service tries to start lighthttpd just an SSL call when the server is already running and HTTP works without a problem.

`as pihole    | ./run: line 32:   597 Segmentation fault      (core dumped) lighttpd -D -f /etc/lighttpd/lighttpd.conf
`
```
root@398574520ee7:/# lighttpd -D -t -f /etc/lighttpd/lighttpd.conf
Syntax OK
root@398574520ee7:/# lighttpd -D -t -f /etc/lighttpd/external.conf
Syntax OK

```

**Comment by rdwebdesign** [comment]
That's why I said "Regarding SSL warnings".

I knew the warnings would be fixed, but I wasn't sure about the rest. We need to investigate more.

**Comment by thomasmerz** [comment]
@dschaper just released 2022.04.02 some minutes ago - it's still a problem with https 🤷🏻‍♂️ 
```
./run: line 32:   661 Segmentation fault      lighttpd -D -f /etc/lighttpd/lighttpd.conf
```

**Comment by thomasmerz** [comment]
That's indeed a good question… 😉 and I hope its's not only distraction regarding this issue 🤣  
Maybe there are others, too, that only run Pi-hole and not other services so a reverse proxy would only be an additional service that won't bring any benefit for them!? 🤷🏻‍♂️

**Comment by farmerbean** [comment]
Looks like I've opened a duplicate issue on this too https://github.com/pi-hole/docker-pi-hole/issues/1062

**Comment by thomasmerz** [comment]
@rdwebdesign , @PromoFaux , did you already have investigated further? With [latest release](https://github.com/pi-hole/docker-pi-hole/releases/tag/2022.04.3) https for WebGUI is still not working… 😞

**Comment by PromoFaux** [comment]
Sorry, not yet - I don't even have my interface exposed to the internet, let alone behind SSL (even via reverse proxy) so it is difficult to test.

Silly question, if you run `lighty-enable-mod ssl` inside the container, does that do anything?

**Comment by thomasmerz** [comment]
It says:
```
12:35 # pihole bash
root@pihole-nbg1-dc3:/# lighty-enable-mod ssl
already enabled
Run "service lighttpd force-reload" to enable changes
```

And:
```
root@pihole-nbg1-dc3:/# service lighttpd force-reload
/usr/local/bin/service: line 53: force-reload: command not found
root@pihole-nbg1-dc3:/# service lighttpd reload
/usr/local/bin/service: line 53: reload: command not found
root@pihole-nbg1-dc3:/#
```

**Comment by farmerbean** [comment]
running ```lighttpd-enable-mod ssl``` completely killed my WebGUI - I can at least access it via http://IP.add.ress.s

**Comment by farmerbean** [comment]
@thomasmerz 'service lighttpd restart' should be enough

**Comment by PromoFaux** [comment]
> reload: command not found

Yeah, we're mocking the `service` command ([see here](https://github.com/pi-hole/docker-pi-hole/blob/master/s6/service)) so reload is not available there, but as @farmerbean said - restart should do it.

But thanks for being the brave folks that try these things out... it's how we get to the bottom of things.

**Comment by thomasmerz** [comment]
Can this maybe root caused to some **cipher** suites!?
If I find some time, I will investigate which cipher suites this lighttpd version and Firefox will both accept.

The "deprecated" messages can simply be ignored or removed by removing the corresponding lines in ` lighttpd.conf`.

**Comment by farmerbean** [comment]
I ran ```lighttpd-disable-mod ssl``` to get access via http again (for now)

**Comment by thomasmerz** [comment]
@farmerbean http was/is no problem, but https was/is a severe problem…

**Comment by dschaper** [comment]
Really your best option for TLS is to use a reverse proxy in front of Pi-hole. You're already running docker compose so adding in something like nginx-proxy or traefik or caddy is pretty easy and doesn't rely on Pi-hole to be in a configuration that it wasn't designed for.

**Comment by hhessel** [comment]
Hope this doesn't come across as blunt but suggesting to run another docker container just to fix a ootb component that should be working is a bit much. Happy to help or support by any means but I probably takes me three times longer to get to bottom of this given that I need to dig into the details of the image first. Thanks.

**Comment by PromoFaux** [comment]
> Hope this doesn't come across as blunt but suggesting to run another docker container just to fix a ootb component that should be working is a bit much.

Suggestions are just that. Nobody is forcing anybody to do anything in a particular way - but limited time and resources, sometimes all that can be suggested are workarounds.

We've made no claims that one can configure the Pi-hole docker container to use SSL. That it worked on a previous version may just be a happy accident.

The [guide linked in several places here](https://discourse.pi-hole.net/t/enabling-https-for-your-pi-hole-web-interface/5771) is for a bare metal install (and also from 2017)... should it work inside the container? Possibly. But I do not have the time or resources to  mess with my own server configurations to troubleshoot unfortunately. Personally I am using Traefik (though, as mentioned above, not for Pi-hole), and I'm not entirely sure what is wrong with doing such a thing - takes the pain out of things ;)

However, lets not get distracted from the reported issue here, and indeed let's look at this from a different angle. The version of `lighttpd` shipped inside this image is `1.4.59 (ssl)`, claims above are that it was working in `2022.02.1` - in which the version of `lighttpd` was `1.4.53 (ssl)`:

```
pi@dockerpi:~ $ docker run -it --rm --entrypoint bash pihole/pihole:2022.02.1
root@e1dcaa41417b:/# lighttpd -v
lighttpd/1.4.53 (ssl) - a light and fast webserver
root@e1dcaa41417b:/# exit
exit
pi@dockerpi:~ $ docker run -it --rm --entrypoint bash pihole/pihole:latest
root@59243be8dcc1:/# lighttpd -v
lighttpd/1.4.59 (ssl) - a light and fast webserver
```

So I guess what I'm angling at here is that maybe there is an issue with `lighttpd 1.4.59` that was not present in `1.4.53`. It may be worth attempting to downgrade `lighttpd` within the container to rule that out. I'm not sure how to do this, but hopefully it's enough of a hint for someone else to attempt it...

**Comment by PolkaMaPhone** [comment]
I'm running a very similar configuration, and I was running into the same ssl warning -- I addressed the warning by modifying my external.conf in a way similar to the above comment; restricting certain protocols.  

After the changes, the warning went away and https is working fine, so it seems somewhat likely something is going on in your particular configuration. At the very least we know this configuration can work as of the most recent version.

I'm running the 'latest' docker image:
- Pi-hole v5.10 
- FTL v5.15 
- Web Interface v5.12
- lighttpd/1.4.59 (ssl)

Here was my external.conf before:
```
server.modules += ("mod_openssl")
$HTTP["host"] == "pi.hole" {
        setenv.add-environment = ("fqdn" => "true")
        $SERVER["socket"] == ":443" {
                ssl.engine = "enable"
                ssl.pemfile = "/etc/lighttpd/ssl/piholecombined.pem"
                ssl.honor-cipher-order = "enable"
                ssl.cipher-list = "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH"
                ssl.use-sslv2 = "disable"
                ssl.use-sslv3 = "disable"
        }

        # Redirect HTTP to HTTPS
        $HTTP["scheme"] == "http" {
                $HTTP["host"] =~ ".*" {
                        url.redirect = (".*" => "https://%0$0")
                }
        }
}
```


And this is the one that's currently working fine for me:

```
server.modules += ("mod_openssl")
$HTTP["host"] == "pi.hole" {
        setenv.add-environment = ("fqdn" => "true")

        $SERVER["socket"] == ":443" {
                ssl.engine = "enable"
                ssl.pemfile = "/etc/lighttpd/ssl/piholecombined.pem"
            ssl.openssl.ssl-conf-cmd = ("Protocol" => "ALL, -SSLv2, -SSLv3, -TLSv1, -TLSv1.1, -TLSv1.2")
                ssl.honor-cipher-order = "disable"
        }

        # Redirect HTTP to HTTPS
        $HTTP["scheme"] == "http" {
                $HTTP["host"] =~ ".*" {
                        url.redirect = (".*" => "https://%0$0")
                }
        }
}
```

**Comment by farmerbean** [comment]
Thanks @PolkaMaPhone that’s good insight. I've modified mine but still getting the error. I'm using a LE cert.

**Comment by thomasmerz** [comment]
@PolkaMaPhone , sorry, this don't also work over here 😞
@farmerbean , I'm also using a LE cert. Reloading/restarting/stopping within my docker container doesn't work:
```
root@pihole-nbg1-dc3:/# lighttpd reload -f /etc/lighttpd/lighttpd.conf
2022-04-29 09:04:07: network.c.369) can't bind to socket: 0.0.0.0:80: Address already in use
root@pihole-nbg1-dc3:/# lighttpd restart -f /etc/lighttpd/lighttpd.conf
2022-04-29 09:04:17: network.c.369) can't bind to socket: 0.0.0.0:80: Address already in use
root@pihole-nbg1-dc3:/# lighttpd stop -f /etc/lighttpd/lighttpd.conf
2022-04-29 09:04:22: network.c.369) can't bind to socket: 0.0.0.0:80: Address already in use
```

**Comment by hhessel** [comment]
The config of @PolkaMaPhone worked me. @thomasmerz This looks like an unrelated config problem on a first glance.

**Comment by thomasmerz** [comment]
@hhessel , you are lucky 😄 My lighttpd is still coredump'ing with the copy&pasted (and path/filenames adapted) on every https-request 😢 
```
2022-04-29T15:42:37.255611991Z ./run: line 32:   502 Segmentation fault      (core dumped) lighttpd -D -f /etc/lighttpd/lighttpd.conf
2022-04-29T15:42:37.270902287Z Stopping lighttpd
2022-04-29T15:42:37.287269960Z lighttpd: no process found
2022-04-29T15:42:37.292302021Z Starting lighttpd
```

**Comment by hhessel** [comment]
@thomasmerz Might be worth to look into how the cert / pem is built. I'm using LE as well with the following command: cat `/etc/letsencrypt/cer.key /etc/letsencrypt/cert.cer | sudo tee /etc/letsencrypt/cert.pem >/dev/null && chmod 777 /etc/letsencrypt/cert.pem && chmod 777 /etc/letsencrypt/fullchain.cer` (I know I know 777 ;)

**Comment by thomasmerz** [comment]
I've been using this since initial configuration:
```
    ssl.pemfile = "/etc/letsencrypt/fullchain.pem"
    ssl.privkey = "/etc/letsencrypt/key.pem"
```

The files have ever been like this:
```
root@pihole-nbg1-dc3:/# ls -l /etc/letsencrypt/
total 12
-rw-r--r-- 1 root root 5946 Apr  2 16:04 fullchain.pem
-rw-r--r-- 1 root root 3247 Apr  2 16:04 key.pem
```

Cert-files are being reused from my Nextcloud instance and are working fine for Nextcloud, Portainer, … and Pi-hole-docker since 2022.04.01 🤷🏻‍♂️

**Comment by Theliel** [comment]
Okay, I had been trying to find the problem in question for some time without any success, until today. The solution proposed by did not work for me, so I proceeded from scratch from the simplest configuration, based on the latest lighttpd version.

After some testing, I found the root cause, at least I repeat in my case, which was the $HTTP["host"] directive. Simply by removing the conditional directive, and even keeping the configuration it I had originally (with the warnings already mentioned), everything works. 

So I took the opportunity to update the "old" configuration as well. The best of all is that if what we want is to force the maximum degree of security, the configuration is quite simple, just force TLS1.3, and allow the browser to choose the best cipher suite (to take into account that the device you can use for example chacha20)

```
#load openssl
server.modules += ( "mod_openssl" )

$SERVER["socket"] == ":443" {
	ssl.engine  = "enable"
	ssl.pemfile = "/etc/lighttpd/combined.pem"
	ssl.openssl.ssl-conf-cmd = ("MinProtocol" => "TLSv1.3", "Options" => "-ServerPreference")
}

# Redirect HTTP to HTTPS
$HTTP["scheme"] == "http" {
        $HTTP["host"] =~ ".*" {
        url.redirect = (".*" => "https://%0$0")
        }
}

```

All is working fine again

**Comment by thomasmerz** [comment]
@Theliel , awesome! You made my day, my week, my … 😄 Thanks a lot for solving this issue!

**Comment by thomasmerz** [comment]
@yubiuser , because I (or @Theliel?) really would like to update/add/enrich this [FAQ](https://discourse.pi-hole.net/t/enabling-https-for-your-pi-hole-web-interface/5771/113) with information from this issue: is there a chance to re-open this FAQ and add this config for enabling HTTPS for Pi-hole's Web UI?

**Comment by dschaper** [comment]
I've made that topic into a wiki, you should be able to make community modifications.

**Comment by thomasmerz** [comment]
Did I understand you wrong or why is https://discourse.pi-hole.net/tag/wiki still locked (for me) 🤷🏻‍♂️ 
<img width="529" alt="grafik" src="https://user-images.githubusercontent.com/18568381/168379796-27fbeefe-b6f6-4997-a9e0-eff969e8f1b7.png">

**Comment by yubiuser** [comment]
Please try again

**Comment by gstrauss** [comment]
==> The primary issue here appears to be **broken rPi configuration**

lighttpd 1.4.56 and later reworked the TLS logic to better support openssl 1.1.1 and openssl 3.x, adding features including support for TLS-ALPN-01 ("acme-tls/1") challenges.  Older versions of openssl have all reached end-of-life.

If the rPi lighttpd.conf TLS config was broken, lighttpd 1.4.55 might have failed for TLS connections with broken config conditions.  In lighttpd 1.4.56 to lighttpd 1.4.59, some configurations may have resulted in a crash in a callback underneath the openssl library due to broken Pi lighttpd.conf failing to configure TLS certificates for the socket.  SNI may or may not be provided with TLS ClientHello during TLS negotation, and if a certificate is not configured in lighttpd.conf for the *socket*, then TLS negotation may fail, e.g. if SNI is not provided, or SNI is provided to a host without certs configured.

Those using broken lighttpd.conf TLS configs which wrapped the certificate config inside `$HTTP["host"]` *and* never defined a catch-all TLS certificate *outside* the `$HTTP["host"]` condition have ** *always* ** been partially broken lightptd.conf TLS configurations, but did not cause a crash in lighttpd 1.4.53.

lighttpd 1.4.60 (*released 3 Oct 2021*) contains a fix for a crash with such broken TLS configs:
https://git.lighttpd.net/lighttpd/lighttpd1.4/commit/bc3a2b4e4728f3e9e1a23eaf30eae2add5c0483e

lighttpd 1.4.60 was released almost 7 months prior to this issue being filed.  Everyone troubleshooting here with lighttpd 1.4.59 unfortunately spent a lot of time troubleshooting their broken TLS configs when lighttpd 1.4.60 and later would not have crashed and would have provided a more descriptive error message.

rPi is based on Ubuntu and Ubuntu is based on Debian.  Ubuntu and Debian distros are notoriously slow picking up new releases, and Ubuntu and Debian *almost never* backport software to stable distro releases except for security fixes, and even then such updates are often delayed by months or longer.

If you are using an image, please consider using the latest stable releases of your application software, including lighttpd.  You should not depend on your distros to keeping you updated, especially not if your distro is based on Ubuntu or Debian.

---

https://wiki.lighttpd.net/HowToSimpleSSL recommends configs using Let's Encrypt with:
`ssl.pemfile = "/path/to/fullchain.pem"`
`ssl.privkey = "/path/to/privkey.pem"`
and this has been available in lighttpd since lighttpd 1.4.53, released in Jan 2019, almost **4 years ago**
What are you using in your rPi lighttpd.conf?  Do you still run scripts as root to combine those public cert and key when lighttpd prefers to directly use the files provided by Let's Encrypt?

More details, descriptions, and best practices for TLS configuration in lighttpd.conf can be found at https://wiki.lighttpd.net/Docs_SSL

The current stable release of lighttpd is lighttpd 1.4.67, released Sep 2022.

**Comment by thomasmerz** [comment]
@gstrauss , I already have posted my solution (very similar, but less detailed than your update here): https://discourse.pi-hole.net/t/enabling-https-for-your-pi-hole-web-interface/5771/116

**Comment by PromoFaux** [comment]
@thomasmerz you should be able to edit the OP of that post directly as it is a wiki post - Would you mind editing it to take into account the information in the post you have just linked? Otherwise it just gets buried :)

**Comment by thomasmerz** [comment]
There's no edit-button for me on my wiki-post… 🤷🏼‍♂️ And the link is the link to the wiki post? Or do you want to have added some more information provided by gstrauss?

**Comment by PromoFaux** [comment]
Sorry, on the very top post of the thread on discourse - not your own post in that thread. A wiki post allows any authenticated user to modify the original contents of the post

![image](https://user-images.githubusercontent.com/1998970/206693713-bb05c88f-1dc4-424e-b5b8-59b61b61134b.png)

**Comment by thomasmerz** [comment]
Found it! Hopefully I've edited it to your satisfaction.

**Comment by gstrauss** [comment]
@thomasmerz, I saw your post, but it did not pinpoint the reasons:
- running old lighttpd software
- using a broken rPi lighttpd.conf config

Also, since lighttpd 1.4.50 (released Aug 2018), redirecting from http to https is more clearly and directly written as:
```
$HTTP["scheme"] == "http" {
    url.redirect = ("" => "https://${url.authority}${url.path}${qsa}")
}
```

All of this is documented on https://wiki.lighttpd.net/

lighttpd TLS config reference can additionally be found at
https://ssl-config.mozilla.org/#server=lighttpd&config=modern&guideline=5.6

**Comment by thomasmerz** [comment]
@gstrauss , I'm not a 100% sure, but I really think there has never been any "rPi lighttpd.conf config"; at least not in my docker setup!?
Anybody who wants to enable HTTPS for Pi-hole Web Interface needed and still need (?) to add it by him/herself. You are refering to the wiki page that someone started to explain how Pi-hole can be enabled, which used a "broken rPi lighttpd.conf config" since not "running old lighttpd software" since docker image 2022.04.01.  

But as @rdwebdesign [wrote on Nov, 4th](https://discourse.pi-hole.net/t/enabling-https-for-your-pi-hole-web-interface/5771/125), there will be a `lighttpd.conf` being shipped with Pi-hole… 🤷🏼‍♂️

**Comment by gstrauss** [comment]
@thomasmerz:
I am a lighttpd developer and provide both the official lighttpd releases and the official lighttpd documentation.  When bugs are reported on the official lighttpd site (see https://wiki.lighttpd.net/), the bugs get fixed in the official lighttpd source and are released in a new official lighttpd release.

What then happens is that operating system distributions ("distros") have to pick up the new release and package it for those who use the distro.  Just about ANYTHING and EVERYTHING else having to do with packaging on specific distros is out of my control, though I do try to provide packaging advice when asked.  (That is an open invitation, @rdwebdesign)

The crash reported in this issue by OP was reported *7 months* after the bug was *fixed and released* in lighttpd 1.4.60.

> I'm not a 100% sure, but I really think there has never been any "rPi lighttpd.conf config"; at least not in my docker setup!?

Debian packages lighttpd.  Ubuntu derives from Debian.  I believe that rPi derives from Ubuntu.  The lighttpd package on rPi includes a lighttpd.conf.  I believe that pi-hole derives from rPi.

I do not know who creates your docker image or from what specific part of the above (poorly) maintained distro chain it comes, but if you are running lighttpd, then you have a lighttpd.conf that was likely provided by the packager who packaged lighttpd and lighttpd.conf on the base distro on which the image is based.

**Comment by thomasmerz** [comment]
Hi @gstrauss , nice to meet a lighttp dev over here 👍🏻  
As you can see from my screenshots there's no conf shipped within the Docker Image for Pi-hole 🤷🏻‍♂️ Maybe you can help the Pi-hole devs over here!? I'm just a user, issuer, contributor.

![image](https://user-images.githubusercontent.com/18568381/206804006-3e609708-1b87-45cf-85cb-55b0bfc40508.jpeg)

![image](https://user-images.githubusercontent.com/18568381/206804037-5650b1e7-9aaa-4f95-bd23-b5d731ca5c11.jpeg)

**Comment by PromoFaux** [comment]
The `lighttpd.conf` file that ships in this container is straight out of the configuration for a bare-metal Pi-hole install (https://github.com/pi-hole/pi-hole/blob/master/advanced/lighttpd.conf.debian)

For the bare metal installs - we generally try to support whatever the supported version of the operating system is (See [here](https://docs.pi-hole.net/main/prerequisites/#supported-operating-systems) for the list of operating systems we test against). We are not generally in the habit of installing newer package versions onto the users operating system - though there is nothing stopping folk from investigating doing such a thing themselves.

The docker install is effectively the same as a Debian 11 (that's full Debian, not Raspberry Pi OS) with a few tweaks to make it work on Docker, and so the version of `lighttpd` [that ships in the container](https://github.com/pi-hole/docker-base-images/blob/master/docker-pi-hole-base/Dockerfile#L29) is whatever the version of `lighttpd` is on Debian 11 at the time the container is built (`lighttpd/1.4.59 (ssl)` at the time of writing)

If there is a pressing need, we could maybe look at switching the base of the image to Ubuntu 22.04 instead of Debian - as that appears [to ship with a newer version of lighttpd](https://pkgs.org/search/?q=lighttpd)

**Comment by rdwebdesign** [comment]
@gstrauss

Pi-hole is not a distro, but it uses lighttpd as a dependency to run our Web Interface.

The main problem we face with Pi-hole + lighttpd is: 

Pi-hole runs on many different distros and we aren't able to guarantee our users will always have the most recent lighttpd version. Some distros are officially still using older packages.

Because we run on many different distros, we are not able to know if there is a `lighttpd.conf` and how this file will look like. To circumvent this doubt we create our own `lighttpd.conf`.

I'm open to discuss better ways to do it, if you have some advice.

**Comment by gstrauss** [comment]
@rdwebdesign thanks for the invite.  I am 'gstrauss' on discourse.pi-hole.net, so please resend invite to that user.  Thanks!

lighttpd is designed as a modular web server.  The official lighttpd source code provides an example of a modular way to configure lighttpd using multiple files in `/etc/lighttpd/conf.d/`.  Many distros -- including Debian and Ubuntu -- use this pattern.

Whoever created the rPi lighttpd package (probably a long, long time ago) probably has not kept up with Debian and Ubuntu, or many other distros following patterns for multiple entities contributing parts of the lighttpd configuration.

I recently contributed an updated base lighttpd.conf to OpenWRT:
https://github.com/openwrt/packages/pull/19995
The minimal base configuration in lighttpd.conf includes `/etc/lighttpd/conf.d/*.conf` and various apps can drop in their own files for configuring a namespace (e.g. `/myapp/`) for their app.

For rPi, I think the next steps would be to identify who might be able to assist with modifying the rPi lighttpd package.  Do you know who that might be?

> The docker install is effectively the same as a Debian 11 (that's full Debian, not Raspberry Pi OS) with a few tweaks to make it work on Docker, and so the version of `lighttpd` [that ships in the container](https://github.com/pi-hole/docker-base-images/blob/master/docker-pi-hole-base/Dockerfile#L29) is whatever the version of `lighttpd` is on Debian 11 at the time the container is built (`lighttpd/1.4.59 (ssl)` at the time of writing)
> 
> If there is a pressing need, we could maybe look at switching the base of the image to Ubuntu 22.04 instead of Debian - as that appears [to ship with a newer version of lighttpd](https://pkgs.org/search/?q=lighttpd)

lighttpd 1.4.59 was released almost 2 years ago.  If someone using pi-hole complains about a bug in pi-hole that you fixed and released in the past 2 years, you tell them to upgrade to a newer version of pi-hole which fixes the bug, don't you?  As I said above, this issue (#1046) was posted *7 months* after the issue was fixed and released in lighttpd 1.4.60.  As I write this, it is now 14 months since lighttpd 1.4.60 was released and you don't see lighttpd 1.4.60 in Debian Buster, and you are not going to see lighttpd 1.4.60 in Debian Buster because Debian Buster is not maintained except possibly for security updates.

I hope that I have made it abuntantly clear that any "stable" release of Debian or Ubuntu is equivalent to almost entirely "unmaintained".  It is awful devops for those distros to equate "no changes unless CVE critical" with "maintained" since quality-of-life software usage suggests that when you make an improvement in your software, you do so for users to be able to use those improvements.

Since one way to obtain pi-hole is through an image, may I make the suggestion that the image use Debian Testing?

Ubuntu is usually behind Debian Testing in updating lighttpd.  Again, like Debian, Ubuntu "stable" releases are often "unmaintained" except for security updates.

**Comment by PromoFaux** [comment]
_Apologies in advance for the wall-of-text™_

> Whoever created the rPi lighttpd package (probably a long, long time ago) probably has not kept up with Debian and Ubuntu, or many other distros following patterns for multiple entities contributing parts of the lighttpd configuration.

```
pi@dockerpi:~ $ lighttpd -v
lighttpd/1.4.59 (ssl) - a light and fast webserver
```

The currently available `lighttpd` package version in Raspberry Pi OS is the same as the currently available version in Debian 11, so I'm not really sure what you're getting at here - but if you're looking for someone to petition, I would start at https://www.raspberrypi.com/contact/

I get your gripes with the whole package/release cycle employed by debian - but it is beyond our control for the most part. Really, all Pi-hole needs is a webserver. `lighttpd` just happens to be the one that was chosen at the beginning of the project. The install script adds one and basic configuration to enable the web interface to work on a local network - and that's it. We added in a reference `external.conf` at one point so that users could customise this without us munging their tweaks every update.

There is even an option in the install script to skip installing a webserver all together - as some users would prefer to just configure their existing webserver to work. All the install script is doing is adding a layer of convenience to lower the barrier to entry to those that might get put of by: "To use Pi-hole, first you need to manually install a bunch of dependencies and configure them by following these documents" vs "Run the install script - you're good to go".  There are even some community provided guides [[1]](https://docs.pi-hole.net/guides/webserver/nginx/), [[2]](https://docs.pi-hole.net/guides/webserver/caddy/), [[3]](https://docs.pi-hole.net/guides/webserver/traefik-nodocker/) on setting up other webservers to work with Pi-hole.

Where things start to get fun is when the more advanced users start trying to change things - and I applaud that. It helps us to learn where we can make improvements to our supplied configurations if they are necessary. One of the greatest things about open source projects is that we can all learn from each other freely.

We have to cater to a wide range of users/abilities - not just the advanced users. An advanced user who wants to add in a manual SSL configuration (versus just setting up a reverse proxy and terminating SSL there - which is what I would do!) should have no issue in installing a newer version of `lighttpd` themselves - but unless there is a show stopping bug in the currently packaged version of `lighttpd` for Debian, we wont be making changes to the install script to grab a newer binary from some other repo/compile it from source as part of the install process - it adds a step of complexity that _most people_ don't depend on.

The next major release of FTL will also embed a web server directly into the binary, which means we will need to depend even less on whatever the distro version is (https://github.com/pi-hole/FTL/pull/659). It's a long time coming, but we're getting closer to a single binary solution that does not have any additional dependencies.

 > Since one way to obtain pi-hole is through an image, may I make the suggestion that the image use Debian Testing?

I'd be very hesitant to do this, despite your own opinions on what does and doesn't define a stable distro, but that's not to stay we can't maybe look at an additional tag while still keeping the main image based on Debian 11 - I will look into it. but in the meantime I think the effort should be focussed on firming up the base config that we ship over on the main repo ([pi-hole/pi-hole](https://github.com/pi-hole/pi-hole))

The main reason that this docker image is currently set up the way it is is to make it easier to maintain. The less it deviates from the core Pi-hole project, the less work we have to do when it comes to new releases - and to be honest, time is rather short these days. We got to a point at one point where development all but ground to a halt on this image, and I would really rather not get back into that situation again by making it deviate from the base install too much.

**Comment by gstrauss** [comment]
@PromoFaux thank you for your comments.

> The currently available lighttpd package version in Raspberry Pi OS is the same as the currently available version in Debian 11, so I'm not really sure what you're getting at here

Yes, and the lighttpd version available is old.  It is static.  It is effectively unmaintained.  That is very unfortunate for me, for you, and for end-users who trip over bugs that were fixed months or years ago.  Nobody should consider this chain well-maintained.  (And nobody is saying that it is entirely your fault or my fault)  It is a bunch of thorny problems, but problems that should at least be recognized and acknowledged, or else the situation can not even start to be improved.)

A bit off-topic from the original post, but related to the configuration mechanisms that resulted in OPs issue:

> Really, all Pi-hole needs is a webserver. lighttpd just happens to be the one that was chosen at the beginning of the project. The install script adds one and basic configuration to enable the web interface to work on a local network - and that's it. We added in a reference external.conf at one point so that users could customise this without us munging their tweaks every update.

The choices are historic and are suboptimal.  There are multiple ways that could be used to configure lighttpd, or any other webserver.  The historic and suboptimal method chosen at the beginning of the project, which *overwrites* the distro package default, is very unfriendly.  Whether using lighttpd or some other equally capable web server, the web server is not the issue, but rather the suboptimal mechanism pi-hole has chosen to configure it.

Related to my statement above about acknowledging issues or suboptimal choices before they can be fixed, do the pi-hole developers consider *overwriting* the distro package default config (for lighttpd) to be suboptimal?  Do the pi-hole developers consider external.conf to be suboptimal when better configuration mechanisms exist (/etc/lighttpd/conf.d/* on Fedora and /etc/lighttpd/conf-enabled/* on Debian) ?  Would pi-hole developers work with me (lighttpd developer) to improve the pi-hole choices for configuring lighttpd?

> We have to cater to a wide range of users/abilities - not just the advanced users. An advanced user who wants to add in a manual SSL configuration ... should have no issue in installing a newer version of lighttpd themselves

An advanced user is not necessarily an expert in everything.  While I personally consider building dpkg or rpms to be straightforward, setting up a build environment and going through the steps represents a barrier to entry for many users (some who are advanced in other ways) if they have not invested the time to learn or do so.  This is not something we should avoid imposing onto end-users, even advanced end-users.

>  - but unless there is a show stopping bug in the currently packaged version of lighttpd for Debian, we wont be making changes to the install script to grab a newer binary from some other repo/compile it from source as part of the install process - it adds a step of complexity that most people don't depend on.

I am not asking that pi-hole does so.  I am trying to figure out how to make it better.  If you provide a mechanism to upgrade pi-hole more than once every 2+ years, is there some way or ways that I can contribute to your build or image process to make it easier for average users to obtain an updated version of lighttpd (or nginx or caddy or whatever) more than once every 2+ years when a new Debian release comes out?

> The next major release of FTL will also embed a web server directly into the binary ... It's a long time coming, but we're getting closer to a single binary solution that does not have any additional dependencies.

Are pi-hole devs trying to workaround these problems by writing a pi-hole web server?  Given the limited development resources and the historic suboptimal choices in configuring lighttpd, is this the best use of development resources?  Is there an area where pi-hole developers have expertise?  Another option would be shipping a standalone or static version of lighttpd (or some other web server) which is maintained by the domain experts who write web servers.  For example, `git instaweb` supports multiple web servers (and defaults to lighttpd), and is able to do so without overwriting the system /etc/lighttpd/lighttpd.conf.

pi-hole could do somethings better than it does now with regards to configuring the lighttpd web server.

>> Since one way to obtain pi-hole is through an image, may I make the suggestion that the image use Debian Testing?

> I'd be very hesitant to do this, despite your own opinions on what does and doesn't define a stable distro, but that's not to stay we can't maybe look at an additional tag while still keeping the main image based on Debian 11 - I will look into it. but in the meantime I think the effort should be focussed on firming up the base config that we ship over on the main repo ([pi-hole/pi-hole](https://github.com/pi-hole/pi-hole))

I am trying to provide some alternative options and food for thought with @rdwebdesign on discourse if you'd like to join that conversation.  My goal is similar to yours: robust, maintainable (and maintained!) systems without unnecessary complexity.

**Comment by PromoFaux** [comment]
On historic (suboptimal) choices, I am largely in agreeance. When Pi-hole was first invented way back in 2016 - it was a) a much smaller project, and b) designed to be the sole application/use of the Raspberry Pi it was installed on - so stuff like configuration overwriting was not so much of a worry - beacuse the idea was that one would install it on an SD card freshly flashed with Raspbian and go from there.

As the project has grown - so, too, has the range of devices and operating systems that people install Pi-hole on. We're not adverse to changing things, so long as we are still able to support things.

I am not so stubborn as to be of the "It's this way because it's always been this way, and it will continue to always be this way" mindset.

> Are pi-hole devs trying to workaround these problems by writing a pi-hole web server?

Good lord, no - we are none of us web server developers. @DL6ER has chosen to embed: https://github.com/civetweb/civetweb, he may or may not wish to chime in with why he chose that one over anything else.

If you're already having a conversation about config improvments on Discourse, by all means invite me in - I would be interested to see where we can improve. And I know we definitely can improve in this area. That we overwrite the config has been a long standing complaint - it's just not an area of the code we've touched for a while due to the planned future changes in how the web interface is served. Help is always appreciated for sure - and to reiterate my previous statement:

> One of the greatest things about open source projects is that we can all learn from each other freely.

So lets learn!

**Comment by gstrauss** [comment]
@rdwebdesign, @PromoFaux, this past Mon evening I mocked up a mini-application in lua for use with lighttpd mod_magnet.  It would appear from my quick testing that this could possibly replace all of the pi-hole-specific lighttpd config with what I consider a much less invasive lighttpd include file to be able to more seamlessly integrate with existing lighttpd configs serving other vhosts.

CentOS 8, CentOS 9, Fedora 35, Fedora 36, Fedora 37, and Debian 10 all have a package for lighttpd-mod-magnet, and Debian 11 and later include lighttpd mod_magnet in the package lighttpd-modules-lua, so I see using a small pi-hole lua script as a potential option to consider not just for pi-hole disk images, but for installations on existing systems, too.

The lua script I wrote theoretically may work with versions of lighttpd mod_magnet back to 2006.
https://github.com/gstrauss/pi-hole/blob/lighttpd-lua/advanced/pihole.lua

Please let's continue the discussion in the discourse, or as an issue in my fork of pi-hole (https://github.com/gstrauss/pi-hole), as OP's issue here has resolved with a config change and this github issue has been marked "Closed".
