### ISSUE TITLE
Unhealthy Healthcheck after Pihole Update

### ISSUE THREAD

**Issue by LacoDev** [pi-hole/docker-pi-hole#1048]
### Versions

- Pi-hole:  v5.9.1
- AdminLTE:  v5.11
- FTL:  v5.14

### Platform

- OS and version:  linux armv7l Raspbian GNU/Linux 10 (buster)

- Platform:  Raspberry Pi

### Expected behavior

After updating pihole complete functionality as before with an healthy healthcheck

### Actual behavior / bug

time.c:132: Operation not permitted timer.c:619: fatal error: RUNTIME_CHECK(isc_time_now((&now)) == 0) failed Aborted (core dumped)

Pihole with slowly recovering functionality, heat spikes of the cpu, Unknown Status in Menu bar + the above error of an unhealthy healthcheck

### Steps to reproduce

1. recreate docker container with latest pihole image
2. See the health check
3. Log in the dashboard

## Debug Token

- Debug was sucessful but failed to upload...

**Comment by rdwebdesign** [comment]
Apparently your pi-hole is not running correctly.

Please, could you try `pihole/pihole:2022.04.2beta` image (no need to add NET_ADMIN capability)?

**Comment by martinikolaev** [comment]
> Apparently your pi-hole is not running correctly.
> 
> Please, could you try `pihole/pihole:2022.04.2beta` image (no need to add NET_ADMIN capability)?

I have same issue latest release, with beta version its all fixed now! Thank you.

**Comment by LacoDev** [comment]
> 

Sadly still the same issue… I can’t tell why its happening… When I reverse the version to the docker image pihole/pihole:2022.02.1 everything works fine

**Comment by rdwebdesign** [comment]
What docker version are you using?

**Comment by leachimus** [comment]
Same problem here. After the autoupdate to the current version, the web interface and the queries go crazy. Also the active status does not seem to work correctly. It appears after activate and reload, unknown.
When I went back to version pihole/pihole:2022.02.1, everything worked fine again.

I use OpenMediaVault 5 with all fixes. And further I have...

Raspbian GNU/Linux 10 (buster) armv7l
Raspberry Pi 4 Model B Rev 1.4 
Kernel: 5.10.103-v7l+ 
Docker version 20.10.14, build a224086

**Comment by dschaper** [comment]
Try `2022.04.2beta`

**Comment by LacoDev** [comment]
> What docker version are you using?

20.10.12 (API: 1.41)

**Comment by leachimus** [comment]
> Try `2022.04.2beta`

This is my probem. it don't work. Only pihole:2022.02.1 work fine.

I would have to upgrade my entire system to Bullseye, which I don't have time to do at this time. I hope you can find a working workaround for now.

**Comment by AcedExplorerABL** [comment]
If this is of any help to someone like me who does not have a lot of time to understand and fix the (seemingly) broken PiHole docker update.

I am on OMV 5.6.26-1
Docker 5:20.10.14~3-0~debian-buster
Portainer 2.11.1
The only PiHole image that is working for me is 2022.02.1
I also had to change the DNSMASQ_USER to "root" in the container settings. Not 100% sure if this was required. If you get the sudo errors, this should help.

Interestingly, Portainer shows the image version as 2022.02.1 but the PiHole admin page identifies itself with the Docker tag 2022.04.01

**Comment by leachimus** [comment]
> If this is of any help to someone like me who does not have a lot of time to understand and fix the (seemingly) broken PiHole docker update.
> 
> I am on OMV 5.6.26-1 Docker 5:20.10.14~3-0~debian-buster Portainer 2.11.1 The only PiHole image that is working for me is 2022.02.1 I also had to change the DNSMASQ_USER to "root" in the container settings. Not 100% sure if this was required. If you get the sudo errors, this should help.
> 
> Interestingly, Portainer shows the image version as 2022.02.1 but the PiHole admin page identifies itself with the Docker tag 2022.04.01

I use the same configuration as you. The thing with the Docker tag is the label.  When replacing the container in Portainer, delete all labels and the ENV that are not absolutely necessary. Then the current data will be generated automatically.

**Comment by 91ajames** [comment]
hmmmm. no issue here. did run into a snag on my other pc's thou. had issues connecting to any site. Refresh ipconfig and all that. Had the ethernet disconnect and pc reboot twice. Everything here works fine. There was an issue but it has disappeared from messages. Might of freaked out when updating and resizing caused 90% of the sd card. or at least in the logs.

[2022-04-03 00:02:32.965 499M] Resizing "FTL-queries" from 2162688 to (53248 * 44) == 2342912 (/dev/shm: 3.2MB used, 67.1MB total, FTL uses ##MB)
non stop

But its at 61.9%.

Asus Tinkerboard - TinkerOS

---
Only thing I wish it kept in was the ipv6 connections just for obvious stats. Every update from pihole, I would need to re-enter the optional ipv6 every time for unbound. Its in the docker settings. Even the config script I made wouldn't be auto added in pihole for whatever reason but works for DNS1 & DNS2. Thought DNS3 & DNS4 would work. Other than why add ipv6 in there at all when its not really necessarily? Just saying. Again, stats sake.

**Comment by rdwebdesign** [comment]
@AcedExplorerABL 

I'm not sure this will work, but since you are using Portainer, my suggestion is to create a new container from zero.
Portainer usually retains old ENV VARs and Labels.

Please, try to remove you container completely, delete the local image and create the container again (pulling a fresh image).

**Comment by jbhorner** [comment]
I also had nothing but issues with this version. Gravity wouldn't update, the ability to manage requests ceased working after a period of time, and the web interface was odd. (Status would go to unknown, and the "Activate" option would appear. This was also true for the beta noted above. I reverted to 2022.02.1 and have had no issues.

**Comment by throwabird** [comment]
Can also confirm pretty much the exact behavior @jbhorner described. It also seemed to completely occupy a core of processing power.
I also tested it with a fresh install using https://github.com/pi-hole/docker-pi-hole/blob/master/docker-compose.yml.example resulting in the same behavior.
Reverting to `pihole/pihole:2022.02.1` resolved the issue for now.

**Comment by PromoFaux** [comment]
> latest version aswell as the beta.

They're basically the same image.

Have you checked the upgrade notes on the readme? If your host OS is buster then you'll need to :) 

https://github.com/pi-hole/docker-pi-hole#upgrade-notes

I have also added this as an important note to the release notes for `2021.04.2`

**Comment by jbhorner** [comment]
> Have you checked the upgrade notes on the readme? If your host OS is buster then you'll need to :)

Upgrading to Bullseye from Buster can be a pretty heavy lift, as the only "official" way to do so is to start fresh. Ultimately, this is what I had to do...imaged another SD with Bullseye, and then migrated several things from Buster. There are documented methods to do an in-place upgrade, but my attempt at that yielded more problems (and time) than simply doing it the official way.

I don't know what the guidelines are for including something in a readme versus release notes. For something like this, I personally feel it should be in the release notes. I review those between updates for most things. Readme files are, to a very high percentage for me, generally not very useful unless new to an initial install, etc. But, that could just be me.

**Comment by PromoFaux** [comment]
> I have also added this as an important note to the release notes for `2022.04.2`

They have been (as of my previous post) retrospectively added to the release notes. Unfortunately it was not an issue were were 100% aware of at the time of release, still working on the finer details in these issues. You also do not have to do an upgrade from buster to bullseye, rather it's to do with the version `libseccomp`, which can be updated via backports - though I cannot officially endorse option this as I don't know what effects it may have on your system (should be fine, but I wouldn't want to guarantee it!)

**Comment by Vodalex** [comment]
Hello everyone. I have deleted the volumes and created the container from scratch. Unfortunately with the latest pihole the container ist still unhealthy. Only using 2022.02.1 pihole fixes the problem. Even if I enter root as DNSMASQ_USER.
Will there be a fix for it?

**Comment by douglasshepherd** [comment]
Hi all, I have been having this issue for a couple of months now with no resolution.  Am I to understand that the primary issue is that OMV's docker version is buster and needs to be upgraded to Bullseye?  
I don't do a ton with OMV and working within it is unclear to me.  For instance, it doesn't offer the chance to upgrade Docker (as far as I can tell) only to install it within the web GUI-interface. 
I am running OMV 5.6.26-1 (Usul) on a Pi4b
system: Linux raspberrypi 5.10.103-v7l+ #1529 SMP Tue Mar 8 12:24:00 GMT 2022 armv7l GNU/Linux
omvextrasorg 5.6.6
Docker: 5:20.10.14~3-0~debian-buster
Portainer 2.11.1
Currently working pihole image: pihole/pihole:2022.02.1

Installing newer pihole images returns unhealthy image and the time on the pihole (when i was able to get the newer versions  running a month or so back) operates with incorrect time as it could not contact NTP. 

Any thoughts would be appreciated.  Thank you all for your work on these projects!

**Comment by rdwebdesign** [comment]
What is the `docker version` output on your system?

**Comment by douglasshepherd** [comment]
Client: Docker Engine - Community
 Version:           20.10.14
 API version:       1.41
 Go version:        go1.16.15
 Git commit:        a224086
 Built:             Thu Mar 24 01:48:44 2022
 OS/Arch:           linux/arm
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.14
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.15
  Git commit:       87a90dc
  Built:            Thu Mar 24 01:46:45 2022
  OS/Arch:          linux/arm
  Experimental:     false
 containerd:
  Version:          1.5.11
  GitCommit:        3df54a852345ae127d1fa3092b95168e4a88e2f8
 runc:
  Version:          1.0.3
  GitCommit:        v1.0.3-0-gf46b6ba
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**Comment by rdwebdesign** [comment]
There is a known issue (caused by a [recent `docker` update](https://github.com/moby/moby/issues/43420#issuecomment-1077870013)) when you run a new docker version (`>= 20.10.14`) on a `buster` system.

Please read our [Upgrade Notes](https://github.com/pi-hole/docker-pi-hole/blob/c4b105853ce19d67d8ac9890beb897288725dcb8/README.md#upgrade-notes) (second item).

Our main suggestion to fix this is to upgrade your system to `bullseye`.

If you can't upgrade, there is a known workaround (linked at Upgrade Notes - try it at your own risk).

Please, read these 2 comments to understand the workaround:

- https://github.com/pi-hole/docker-pi-hole/issues/1043#issuecomment-1086936352
- https://github.com/pi-hole/docker-pi-hole/issues/1042#issuecomment-1086728157

**Comment by edgd1er** [comment]
`
At 30.06.2022 openmediavault 5.x will become EOL. This means no security/bugfix updates will be released anymore. Please upgrade to 6.x to be up-to-date.
`

If upgrading is possible, the current version 6 has no problem with pihole as omv is based on the latest debian s version.

**Comment by douglasshepherd** [comment]
Ok, this makes more sense to me. I didn’t know that OMV 5 was EOL so soon - I will start planning my upgrades. Thank you both!

**Comment by Vodalex** [comment]
Thanks everyone. I have executed om-release-upgrade and successfully upgraded from 5 to 6 after this the pihole container ist healthy and starting without any problem. Thank you very much

**Comment by leachimus** [comment]
> This issue is stale because it has been open 30 days with no activity. Please comment or update this issue or it will be closed in 5 days.

I have updated to the latest Debian version. It wasn't easy, but it worked in the end and now everything is running again. I believe that sooner or later everyone has to take this step.
